---
- name: cpp project playbook
  hosts: all
  tasks:
    - name: Create directory
      win_file:
        path: C:\javaproject
        state: directory
    - name: copy file to Windows VM
      win_copy:
        src: /home/shashankmsy/test/files/spring-petclinic.zip
        dest: C:\javaproject
        remote_src: no
    - name: unziping the java folder
      win_unzip:
        src: C:\javaproject\spring-petclinic.zip
        dest: C:\javaproject
        remote_src: yes
